### ISSUE TITLE
P5 version invalid

### ISSUE THREAD

**Issue by lb42** [GutenbergSource/66829-Loos-Gentlemen-prefer-blondes#2]
The table of printing info starting like this
~~~~
<table rows="12"
     headrows="0" cols="2">
     <row>
      <cell row="1" cols="1" rows="1" col="1">First printing, November, </cell>
      <cell row="1" cols="1" rows="1" col="2">1925</cell>
     </row>
~~~~
is invalid TEI: the attributes table@headrows  cell@row and cell@col are not defined
(and wouldn't this be better as a list than a table?)

**Comment by jhellingman** [comment]
Will adjust my conversion pipeline to P5 drop those things. In the pipeline, I add these things, so I can apply the correct border styles to table cells in the generated HTML, even when tables have column or row spans. I should split of the P5 generation before introducing these.

Semantically it is a list. Since the source aligned the dates, I used a table to reproduce that. Looking at the source again, it could also be considered a fully justified list, with those wide spaces...

**Comment by jhellingman** [comment]
Changed the table to a list; used CSS in the HTML output to recreate the justification effect in the source (which is even closer now than it was; PG is highly conservative in accepting CSS3: only when features reach the REC status, they can be used).

Filtered out those additional attributes in the P4 to P5 conversion.
