### ISSUE TITLE
use of choice inappropriate

### ISSUE THREAD

**Issue by lb42** [GutenbergSource/66829-Loos-Gentlemen-prefer-blondes#3]
Things like this:
~~~~
<choice>
     <sic>encyclopediacs</sic>
     <corr>encyclopedias</corr>
     </choice>
~~~~
It's plausible to tag "encyclopediacs" with `<sic>` I suppose, but using `<corr>` to supply a corrected version (or for that matter `<reg>` for a regularisation)  makes no sense. There is nothing to correct here: it's a deliberate variant form for comic effect. It's certainly not an error.
And there are also lots of other humorous misspellings (for instants, tempramental, bolshevicks, authrodox, negligay ... ) which have not been tagged at all...

**Comment by jhellingman** [comment]
You're right. I will undo this "correction". Oh, wait... In my source it is `<sic corr="...">...</sic>` in many cases. The conversion to `<choice>` actually makes that distinction meaningless. I will reconsider how to tackle this. It is indeed senseless to do it for some, but not for all, and it is a good challenge to do it for all, which would take away much of the charm of this book anyway.

**Comment by jhellingman** [comment]
Fixed this by changing all `<sic corr="...">...</sic>` occurrences with `<orig reg="...">...</orig>`. This gets converted to an appropriate `<choice>` in the P5 edition. Normally you of course would render the `<orig>` in this case; the regularized form does make sense for people searching for certain words.

**Comment by lb42** [comment]
If you do a quick spellcheck of the text, you will find that the existing markup captures maybe 50% or less of the actual (deliberate) spelling variation. There are cases where the same mis-spelled word (try "tempermental") is marked-up in one place but not in another a few lines away from it! I cannot see that this is useful. Do you know on what basis this markup was originally introduced? If it's really so important to flag strange spellings (intended for humorous effect) simply tagging them with `<sic>` would do the job, in my opinion: no need to introduce all the `<choice>` baggage.

**Comment by jhellingman** [comment]
I am aware of that. Consider it an artifact of the production process: at Distributed Proofreaders, volunteers will mark words as suspect, and suggest an alternative. Other volunteers realized these misspellings were intentional (I warned them in the project instructions at PGDP), and thus didn't bother to mark them. While I did preserve the markings in mark-up, I mostly didn't bother to add it for the unmarked items, as I have no direct need for that information. On the other hand, having this tagging doesn't bother me, as I ignore it in the transformations I use (producing HTML and ePub versions; my ePub is different from the one at Project Gutenberg, which takes the route of deriving it from HTML). If somebody in future wishes to make the set complete, they can (I will accept their merge request). Similarly, if somebody would wish to add tagging of personal names, geographic locations, and so on, this can be done without being in the way of other uses. I consider that the beauty of the TEI standard: you can have one source of a text with many aspects marked up. Dropping what you don't need is just one transform away.
